
import { db } from "../db/database";
import type { Payment, PaymentAllocation, PaymentMethod } from "../models/domain";
import { rentLedgerService } from "./rentLedgerService";
import { reconciliationService } from "./reconciliationService";
export interface PaymentAllocationInput { obligationId:number; amount:number; }
export interface PaymentSaveInput { leaseId:number; tenantId?:number; receivedDate:string; amount:number; paymentMethod:PaymentMethod; reference:string; notes:string; allocations:PaymentAllocationInput[]; }
export class PaymentService { async save(input:PaymentSaveInput):Promise<number>{if(!input.leaseId)throw new Error("Select a lease.");if(!input.receivedDate)throw new Error("Received date is required.");if(input.amount<=0)throw new Error("Payment amount must be greater than zero.");const total=input.allocations.reduce((t,a)=>t+a.amount,0);if(total-input.amount>.005)throw new Error("Allocations cannot exceed the payment amount.");const obligations=await db.rentObligations.bulkGet(input.allocations.map(a=>a.obligationId));for(const a of input.allocations){const o=obligations.find(x=>x?.id===a.obligationId);if(!o||o.leaseId!==input.leaseId)throw new Error("An allocation does not belong to the selected lease.");}
const id=await db.transaction("rw",db.payments,db.paymentAllocations,async()=>{const pid=Number(await db.payments.add({leaseId:input.leaseId,tenantId:input.tenantId,receivedDate:input.receivedDate,amount:input.amount,paymentMethod:input.paymentMethod,reference:input.reference.trim(),notes:input.notes.trim(),source:"Manual",status:"Posted",createdAt:new Date().toISOString()} satisfies Payment));const rows=input.allocations.filter(a=>a.amount>0).map(a=>({paymentId:pid,obligationId:a.obligationId,amount:a.amount} satisfies PaymentAllocation));if(rows.length)await db.paymentAllocations.bulkAdd(rows);return pid});await rentLedgerService.refreshAllStatuses();return id;}
async voidPayment(paymentId:number,reason:string):Promise<void>{const payment=await db.payments.get(paymentId);if(!payment)throw new Error("Payment not found.");if((payment.status??"Posted")==="Voided")throw new Error("This payment has already been voided.");const trimmed=reason.trim();if(!trimmed)throw new Error("Enter a reason for voiding the payment.");await db.transaction("rw",db.payments,db.paymentAllocations,db.rentObligations,async()=>{await db.paymentAllocations.where("paymentId").equals(paymentId).delete();await db.payments.update(paymentId,{status:"Voided",voidedAt:new Date().toISOString(),voidReason:trimmed});});await rentLedgerService.refreshAllStatuses();
await reconciliationService.reopenForVoidedPayment(paymentId);}
}
export const paymentService=new PaymentService();
