import { creditService } from "../../services/creditService";
import { currency, escapeHtml } from "../shared/format";
import { createTable } from "../shared/table";

export async function renderCredits(container:HTMLElement):Promise<void>{
 const rows=await creditService.list(); const total=rows.reduce((t,r)=>t+r.remaining,0);
 container.innerHTML=`<div class="page-heading d-flex justify-content-between align-items-end"><div><h1>Unapplied Credits</h1><p class="text-body-secondary mb-0">Find and apply money received but not yet allocated to rent charges.</p></div><div class="text-end"><div class="small text-body-secondary">Available credit</div><div class="metric-value">${currency(total)}</div></div></div><div class="card"><div class="card-body"><table id="credits-table" class="table table-hover align-middle w-100"><thead><tr><th>Received</th><th>Unit</th><th>Tenant</th><th>Reference</th><th>Payment</th><th>Applied</th><th>Available</th><th>Action</th></tr></thead></table></div></div><div id="credit-dialog-host"></div>`;
 createTable("#credits-table",{data:rows,columns:[{data:"receivedDate"},{data:"unitLabel",render:(v:string)=>escapeHtml(v)},{data:"tenantName",render:(v:string)=>escapeHtml(v)},{data:"reference",render:(v:string)=>escapeHtml(v)},{data:"amount",render:(v:number)=>currency(v)},{data:"allocated",render:(v:number)=>currency(v)},{data:"remaining",render:(v:number)=>`<strong>${currency(v)}</strong>`},{data:null,orderable:false,searchable:false,render:(_:unknown,__:unknown,row:any)=>`<button class="btn btn-sm btn-primary apply-credit" data-payment="${row.paymentId}">Apply Credit</button>`}]});
 document.querySelectorAll<HTMLButtonElement>(".apply-credit").forEach(b=>b.addEventListener("click",()=>void openDialog(Number(b.dataset.payment),rows.find(r=>r.paymentId===Number(b.dataset.payment))!,container)));
}
async function openDialog(paymentId:number,row:any,container:HTMLElement){ const obs=await creditService.obligations(row.leaseId); if(!obs.length){alert("This lease has no outstanding charges to receive the credit.");return;} const host=document.getElementById("credit-dialog-host")!; host.innerHTML=`<div class="modal fade show" style="display:block;background:rgba(0,0,0,.4)" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Apply Credit</h5><button class="btn-close close-credit"></button></div><div class="modal-body"><div class="alert alert-info">Available: <strong>${currency(row.remaining)}</strong> · ${escapeHtml(row.unitLabel)}</div><label class="form-label">Outstanding charge</label><select id="credit-obligation" class="form-select mb-3">${obs.map((o:any)=>`<option value="${o.id}" data-remaining="${o.remaining}">${o.rentPeriod} — ${currency(o.remaining)} due</option>`).join("")}</select><label class="form-label">Amount to apply</label><div class="input-group"><span class="input-group-text">$</span><input id="credit-amount" class="form-control" inputmode="decimal" value="${Math.min(row.remaining,obs[0].remaining).toFixed(2)}"></div></div><div class="modal-footer"><button class="btn btn-secondary close-credit">Cancel</button><button id="save-credit" class="btn btn-primary">Apply Credit</button></div></div></div></div>`; const close=()=>host.replaceChildren(); host.querySelectorAll(".close-credit").forEach(x=>x.addEventListener("click",close)); const select=host.querySelector<HTMLSelectElement>("#credit-obligation")!; select.addEventListener("change",()=>{const due=Number(select.selectedOptions[0].dataset.remaining);(host.querySelector("#credit-amount") as HTMLInputElement).value=Math.min(row.remaining,due).toFixed(2)}); host.querySelector("#save-credit")!.addEventListener("click",async()=>{try{await creditService.apply(paymentId,Number(select.value),Number((host.querySelector("#credit-amount") as HTMLInputElement).value)); close(); await renderCredits(container);}catch(e){alert((e as Error).message)}}); }
