export const repositoryConfiguration = {
  buildings: "api",
  locations: "api",
  leases: "api",
  tenants: "api",
  units: "api",
  payments: "api",
  allocations: "api",
  credits: "api",
  rentLedger: "api",
  paymentReceipts: "api",
  bankImport: "api",
  reconciliation: "api",
  dashboard: "api",
} as const;
